version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "contrasena"
    ports:
      - "8080:80"
    depends_on:
      - postgres
